Description of ecm_below_threshold
Home > matlab > enzyme-cost-minimization > fsc_functions > ecm_below_threshold.m
ecm_below_threshold
PURPOSE
function needed for enzyme cost minimization
SYNOPSIS
function [ineq_constraints, eq_constraints] = ecm_below_threshold(fsc_score,xx,pp,u_threshold,x_min,x_max,fsc_options)
DESCRIPTION
 function needed for enzyme cost minimization
CROSS-REFERENCE INFORMATION
This function calls:
ecm_get_score
fsc_inequalities [delta_G_by_RT,eq_cons] = measures_for_enzyme_costs_inequalities(x,N_forward,log_Keq_forward)
fsc_regularisation
This function is called by:
fsc_enzyme_cost_minimization FSC_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution
SOURCE CODE
function [ineq_constraints, eq_constraints] = ecm_below_threshold(fsc_score,xx,pp,u_threshold,x_min,x_max,fsc_options)
% function needed for enzyme cost minimization
a1 = ecm_get_score(fsc_score,xx,pp) + fsc_regularisation(xx,x_min,x_max,fsc_options.lambda_regularisation) - u_threshold;
a2 = fsc_inequalities(xx,pp.N_forward,pp.log_Keq_forward);
ineq_constraints = [a1; a2];
eq_constraints   = [];