Description of fsc_inequalities
Home > matlab > enzyme-cost-minimization > fsc_functions > fsc_inequalities.m
fsc_inequalities
PURPOSE
[delta_G_by_RT,eq_cons] = measures_for_enzyme_costs_inequalities(x,N_forward,log_Keq_forward)
SYNOPSIS
function [delta_G_by_RT,eq_cons] = measures_for_enzyme_costs_inequalities(x,N_forward,log_Keq_forward)
DESCRIPTION
 [delta_G_by_RT,eq_cons] = measures_for_enzyme_costs_inequalities(x,N_forward,log_Keq_forward)
 numerical accuracy for positivity constraints
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fsc_enzyme_cost_minimization FSC_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution
ecm_below_threshold function needed for enzyme cost minimization
ecm_one_run % optimize log concentration profile
SOURCE CODE
function [delta_G_by_RT,eq_cons] = measures_for_enzyme_costs_inequalities(x,N_forward,log_Keq_forward)
% [delta_G_by_RT,eq_cons] = measures_for_enzyme_costs_inequalities(x,N_forward,log_Keq_forward)
%
% numerical accuracy for positivity constraints
epsilon = 10^-10;
delta_G_by_RT = N_forward' * x - log_Keq_forward + epsilon;
eq_cons = [];