Description of fsc_regularisation
Home > matlab > enzyme-cost-minimization > fsc_functions > fsc_regularisation.m
fsc_regularisation
PURPOSE
SYNOPSIS
function f = fsc_regularisation(x,x_min,x_max,lambda)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fsc_enzyme_cost_minimization FSC_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution
ecm_below_threshold function needed for enzyme cost minimization
ecm_one_run % optimize log concentration profile
SOURCE CODE
function f = fsc_regularisation(x,x_min,x_max,lambda)
f = lambda * 0.5 * sum([x - 0.5 * [x_min + x_max]].^2);