Description of ecm_get_score
Home > enzyme-cost-minimization > ecm_functions > ecm_get_score.m
ecm_get_score
PURPOSE
SYNOPSIS
function [u_cost, u] = ecm_get_score(ecm_score,x,pp)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ecm_ecf1 [u_tot, u] = ecm_ecf1(x,pp)
ecm_ecf2s [u_tot, u] = ecm_ecf2s(x,pp)
ecm_ecf2sp [u_tot, u] = ecm_ecf2sp(x,pp)
ecm_ecf3s [u_tot, u] = ecm_ecf3s(x,pp)
ecm_ecf3sp [u_tot, u] = ecm_ecf3sp(x,pp)
ecm_ecf4cmr [u_tot, u] = ecm_ecf4cmr(x,pp)
ecm_ecf4dmr [u_tot, u] = ecm_ecf4cmr(x,pp)
ecm_ecf4geom [u_tot, u] = ecm_ecf4geom(x,pp)
ecm_ecf4smr [u_tot, u] = ecm_ecf4cmr(x,pp)
ecm_mdf [f,u] = ecm_mdf(x,pp)
ecm_min_ecf2s [f, u] = ecm_ecf2s(x,pp)
ecm_min_ecf2sp [f, u] = ecm_min_ecf2sp(x,pp)
This function is called by:
ecm_enzyme_cost_minimization ECM_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution
ecm_below_threshold function needed for enzyme cost minimization
ecm_get_one_u function my_u_it = ecm_get_one_u(it,ecm_score,xx,pp,u_threshold,x_min,x_max,ecm_options)
ecm_one_run % optimize log concentration profile
SOURCE CODE
function [u_cost, u] = ecm_get_score(ecm_score,x,pp)
switch ecm_score,
  case 'mdf',      [u_cost, u] = ecm_mdf(x,pp);
  case 'mfsc2sub', [u_cost, u] = ecm_min_ecf2s(x,pp);
  case 'mfsc2',    [u_cost, u] = ecm_min_ecf2sp(x,pp);
  case 'ecf1',     [u_cost, u] = ecm_ecf1(x,pp);
  case 'ecf2s',    [u_cost, u] = ecm_ecf2s(x,pp);
  case 'ecf2sp',   [u_cost, u] = ecm_ecf2sp(x,pp);
  case 'ecf3s',    [u_cost, u] = ecm_ecf3s(x,pp);
  case 'ecf3sp',   [u_cost, u] = ecm_ecf3sp(x,pp);
  case 'ecf4dmr',  [u_cost, u] = ecm_ecf4dmr(x,pp);
  case 'ecf4smr',  [u_cost, u] = ecm_ecf4smr(x,pp);
  case 'ecf4cmr',  [u_cost, u] = ecm_ecf4cmr(x,pp);
  case 'ecf4geom', [u_cost, u] = ecm_ecf4geom(x,pp);
  otherwise,        u_cost = nan; u = nan * ones(nr,1);
end