Description of ecm_regularisation
Home > enzyme-cost-minimization > ecm_functions > ecm_regularisation.m
ecm_regularisation
PURPOSE
ECM_REGULARISATION - Regularisation term for ECM
SYNOPSIS
function f = ecm_regularisation(x,x_min,x_max,lambda)
DESCRIPTION
 ECM_REGULARISATION - Regularisation term for ECM
 function f = ecm_regularisation(x,x_min,x_max,lambda)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ecm_enzyme_cost_minimization ECM_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution
ecm_below_threshold ECM_BELOW_THRESHOLD - Helper function for enzyme cost minimization
ecm_one_run ECM_ONE_RUN - Perform one ECM run