Description of ecm_enzyme_cost_minimization
Home > enzyme-cost-minimization > ecm_enzyme_cost_minimization.m
ecm_enzyme_cost_minimization
PURPOSE
ECM_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution
SYNOPSIS
function [c, u, u_cost, up, A_forward, mca_info, c_min, c_max, u_min, u_max, r, u_capacity, eta_energetic, eta_saturation] = ecm_enzyme_cost_minimization(network,r,v,ecm_options)
DESCRIPTION
 ECM_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution
 [c, u, u_cost, up, A_forward, mca_info, c_min, c_max, u_min, u_max, r, u_capacity, eta_energetic, eta_saturation] = ecm_enzyme_cost_minimization(network, e, v, ecm_options)
 Input
   network       metabolic network structure (as in Metabolic Network Toolbox)
   r             Kinetic constants (from parameter balancing)
   v             flux mode
   ecm_options   options struct (for fields and default values, see 'ecm_default_options')
 Output
   c                 metabolite concentrations
   c.data            data vector (if provided)
   c.fixed           fixed concentration vector
   c.initial         initial solution vector
   c.[SCORE]         1st column: result from optimising the score [SCORE]
                     other columns: possible sampled solutions
   u                 enzyme levels (all enzymes)
   u.data            data vector
   u.[SCORE]         1st column: result from optimising the score [SCORE]
                     other columns: possible sampled solutions
   up                enzyme levels (only scored enzymes as defined by
                                    ecm_scores.ind_scored_enzymes)
   up.[SCORE]        1st column: result from optimising the score [SCORE]
                     other columns: possible sampled solutions
   u_cost            sum of scored enzyme levels
   u_cost.data       data value
   u_cost.[SCORE]    1st column: result from optimising the score [SCORE]
                     other columns: possible sampled solutions
   A_forward         reaction affinity (in flux direction)
   A_forward.initial    initial solution vector
   A_forward.[SCORE] 1st column: result from optimising the score [SCORE]
                     other columns: possible sampled solutions
CROSS-REFERENCE INFORMATION
This function calls:
ecm_below_threshold ECM_BELOW_THRESHOLD - Helper function for enzyme cost minimization
ecm_get_one_u ECM_GET_ONE_U - Helper function for enzyme variability calculation after enzyme cost minimization:
ecm_get_score ECM_GET_SCORE - Helper function
ecm_get_specific_rates ECM_GET_SPECIFIC_RATES - Helper function
ecm_inequalities MEASURES_FOR_ENZYME_COSTS_INEQUALITIES - Helper function
ecm_one_run ECM_ONE_RUN - Perform one ECM run
ecm_regularisation ECM_REGULARISATION - Regularisation term for ECM
ecm_mdf [f,u] = ecm_mdf(x,pp)
This function is called by:
ecm_simple ECM_SIMPLE - Wrapper script for Parameter Balancing or Enzyme Cost Minimisation