Description of ecm_get_specific_rates
Home > enzyme-cost-minimization > ecm_functions > ecm_get_specific_rates.m
ecm_get_specific_rates
PURPOSE
SYNOPSIS
function rates = ecm_get_specific_rates(ecm_score,x,pp,ind)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ecm_ecf1 [u_tot, u] = ecm_ecf1(x,pp)
ecm_ecf2s [u_tot, u] = ecm_ecf2s(x,pp)
ecm_ecf2sp [u_tot, u] = ecm_ecf2sp(x,pp)
ecm_ecf3s [u_tot, u] = ecm_ecf3s(x,pp)
ecm_ecf3sp [u_tot, u] = ecm_ecf3sp(x,pp)
ecm_ecf4cmr [u_tot, u] = ecm_ecf4cmr(x,pp)
ecm_ecf4dmr [u_tot, u] = ecm_ecf4cmr(x,pp)
ecm_ecf4geom [u_tot, u] = ecm_ecf4geom(x,pp)
ecm_ecf4smr [u_tot, u] = ecm_ecf4cmr(x,pp)
ecm_mdf [f,u] = ecm_mdf(x,pp)
ecm_min_ecf2s [f, u] = ecm_ecf2s(x,pp)
ecm_min_ecf2sp [f, u] = ecm_min_ecf2sp(x,pp)
This function is called by:
ecm_enzyme_cost_minimization ECM_ENZYME_COST_MINIMIZATION - Compute optimal flux-specific enzyme costs for given flux distribution